apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "xds-backend.fullname" . }}
  labels:
    {{- include "xds-backend.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{ toYaml .Values.config | nindent 4 }}