apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.envoyGateway.rbac.clusterRoleName }}
rules:
  - apiGroups:
      - "xdsbackend.wtzhang23.github.io"
    resources:
      - "xdsbackends"
    verbs:
      - "get"
      - "list"
      - "watch"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.envoyGateway.rbac.clusterRoleBindingName }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.envoyGateway.rbac.clusterRoleName }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.envoyGateway.serviceAccountName }}
    namespace: {{ .Values.envoyGateway.namespace }}

