apiVersion: v1
kind: Service
metadata:
  name: {{ include "xds-backend.fullname" . }}
  labels:
    {{- include "xds-backend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.grpcPort }}
      targetPort: grpc
      protocol: TCP
      name: grpc
    - port: {{ .Values.service.httpPort }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "xds-backend.selectorLabels" . | nindent 4 }}
