{{- if .Values.deployment.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "xds-backend.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "xds-backend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- if .Values.service.enablePlaintext }}
    - port: {{ .Values.service.grpcPort }}
      targetPort: grpc
      protocol: TCP
      name: grpc
    {{- end }}
    {{- if .Values.service.tls.enabled }}
    - port: {{ .Values.service.tls.grpcPort }}
      targetPort: grpc-tls
      protocol: TCP
      name: grpc-tls
    {{- end }}
    - port: {{ .Values.service.httpPort }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.metricsPort }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "xds-backend.selectorLabels" . | nindent 4 }}
{{- end }}
